### PR TITLE
add missing __init__.py files and include a manifest file

### PR DESCRIPTION
**Pull request by ahussein**
Fixes: https://github.com/Jumpscale/0-robot/issues/24

### CODE REVIEW

**Comment by zaibon** [comment]
@ahussein I was taking the same kind of approach but you were missing some files.
I send a commit to add them using setup.py directly. MANIFEST.in is generated automatically from there.

**Comment by ahussein** [comment]
According to some stackoverfow entries i checked, using package_data is not the best idea bc it only works with binary packages and not source packages.
A better approach is to use include_package_data=True in setup.py and include the files in the MANIFEST.IN file

**Comment by zaibon** [comment]
From the python documentation : `Changed in version 3.1: All the files that match package_data will be added to the MANIFEST file if no template is provided. `

**Comment by ahussein** [comment]
check this: https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute/14159430

**Comment by zaibon** [comment]
>I have been researching this issue for the past hour and have been trying many approaches. As you say, package_data works for bdist and not sdist. However, MANIFEST.in works for sdist, but not for bdist! Therefore, the best I have been able to come up with is to include both package_data and MANIFEST.in in order to accommodate both bdist and sdist

Ok so we need both, I'll re-add the MANIFEST.in file

**Pull request merged**
